spring:
  application:
    name: tome
 # profiles:
  #  active: ${APPLICATION_PROFILE}
  datasource:
    url: "jdbc:postgresql://localhost:5432/tome"
    username: "brandon"
    password: "sanderson"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
